2022-10-27 16:47:49,212 DEBUG    root            Loaded Command Group: ['gcloud', 'container', 'clusters']
2022-10-27 16:47:49,213 DEBUG    root            Loaded Command Group: ['gcloud', 'container', 'clusters', 'delete']
2022-10-27 16:47:49,233 DEBUG    root            Running [gcloud.container.clusters.delete] with arguments: [--zone: "europe-west3-b", NAME:1: "['12870']"]
2022-10-27 16:47:50,740 DEBUG    urllib3.connectionpool Starting new HTTPS connection (1): container.googleapis.com:443
2022-10-27 16:47:50,985 DEBUG    urllib3.connectionpool https://container.googleapis.com:443 "DELETE /v1/projects/cloud-dev-112233/locations/europe-west3-b/clusters/12870?alt=json HTTP/1.1" 404 None
2022-10-27 16:47:50,994 DEBUG    urllib3.connectionpool Starting new HTTPS connection (1): container.googleapis.com:443
2022-10-27 16:47:51,723 DEBUG    urllib3.connectionpool https://container.googleapis.com:443 "GET /v1/projects/cloud-dev-112233/locations/-/clusters?alt=json HTTP/1.1" 200 None
2022-10-27 16:47:51,889 DEBUG    root            (gcloud.container.clusters.delete) Some requests did not succeed:
 - args: ["ResponseError: code=404, message=Not found: projects/cloud-dev-112233/zones/europe-west3-b/clusters/12870.\nNo cluster named '12870' in cloud-dev-112233."]
   exit_code: 1
Traceback (most recent call last):
  File "/Users/inelpandzic/Dev/Workspace/tools/google-cloud-sdk/lib/googlecloudsdk/calliope/cli.py", line 987, in Execute
    resources = calliope_command.Run(cli=self, args=args)
  File "/Users/inelpandzic/Dev/Workspace/tools/google-cloud-sdk/lib/googlecloudsdk/calliope/backend.py", line 809, in Run
    resources = command_instance.Run(args)
  File "/Users/inelpandzic/Dev/Workspace/tools/google-cloud-sdk/lib/surface/container/clusters/delete.py", line 150, in Run
    raise util.Error(
googlecloudsdk.api_lib.container.util.Error: Some requests did not succeed:
 - args: ["ResponseError: code=404, message=Not found: projects/cloud-dev-112233/zones/europe-west3-b/clusters/12870.\nNo cluster named '12870' in cloud-dev-112233."]
   exit_code: 1

2022-10-27 16:47:51,890 ERROR    root            (gcloud.container.clusters.delete) Some requests did not succeed:
 - args: ["ResponseError: code=404, message=Not found: projects/cloud-dev-112233/zones/europe-west3-b/clusters/12870.\nNo cluster named '12870' in cloud-dev-112233."]
   exit_code: 1

2022-10-27 16:47:51,899 DEBUG    root            Metrics reporting process started...
