2023-07-03 13:14:19,886 DEBUG    root            Loaded Command Group: ['gcloud', 'projects']
2023-07-03 13:14:19,888 DEBUG    root            Loaded Command Group: ['gcloud', 'projects', 'describe']
2023-07-03 13:14:19,889 DEBUG    root            Running [gcloud.projects.describe] with arguments: [--account: "inel.pandzic@percona.com", --configuration: "percona-cloud-dev", --format: "value(name)", PROJECT_ID_OR_NUMBER: "cloud-dev-112233"]
2023-07-03 13:20:00,931 DEBUG    urllib3.connectionpool Starting new HTTPS connection (1): cloudresourcemanager.googleapis.com:443
2023-07-03 13:20:00,945 DEBUG    root            Caught socket error, retrying: HTTPSConnectionPool(host='cloudresourcemanager.googleapis.com', port=443): Max retries exceeded with url: /v1/projects/cloud-dev-112233?alt=json (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x102f98a90>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known'))
2023-07-03 13:20:00,945 DEBUG    root            Retrying request to url https://cloudresourcemanager.googleapis.com/v1/projects/cloud-dev-112233?alt=json after exception HTTPSConnectionPool(host='cloudresourcemanager.googleapis.com', port=443): Max retries exceeded with url: /v1/projects/cloud-dev-112233?alt=json (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x102f98a90>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known'))
2023-07-03 13:20:03,152 DEBUG    urllib3.connectionpool Starting new HTTPS connection (1): cloudresourcemanager.googleapis.com:443
2023-07-03 13:20:03,156 DEBUG    root            Caught socket error, retrying: HTTPSConnectionPool(host='cloudresourcemanager.googleapis.com', port=443): Max retries exceeded with url: /v1/projects/cloud-dev-112233?alt=json (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x102f98090>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known'))
2023-07-03 13:20:03,156 DEBUG    root            Retrying request to url https://cloudresourcemanager.googleapis.com/v1/projects/cloud-dev-112233?alt=json after exception HTTPSConnectionPool(host='cloudresourcemanager.googleapis.com', port=443): Max retries exceeded with url: /v1/projects/cloud-dev-112233?alt=json (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x102f98090>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known'))
2023-07-03 13:20:07,386 DEBUG    urllib3.connectionpool Starting new HTTPS connection (1): cloudresourcemanager.googleapis.com:443
2023-07-03 13:20:07,388 DEBUG    root            Caught socket error, retrying: HTTPSConnectionPool(host='cloudresourcemanager.googleapis.com', port=443): Max retries exceeded with url: /v1/projects/cloud-dev-112233?alt=json (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x102f98090>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known'))
2023-07-03 13:20:07,388 DEBUG    root            Retrying request to url https://cloudresourcemanager.googleapis.com/v1/projects/cloud-dev-112233?alt=json after exception HTTPSConnectionPool(host='cloudresourcemanager.googleapis.com', port=443): Max retries exceeded with url: /v1/projects/cloud-dev-112233?alt=json (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x102f98090>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known'))
2023-07-03 13:25:54,567 DEBUG    urllib3.connectionpool Starting new HTTPS connection (1): cloudresourcemanager.googleapis.com:443
2023-07-03 13:25:54,570 DEBUG    root            Caught socket error, retrying: HTTPSConnectionPool(host='cloudresourcemanager.googleapis.com', port=443): Max retries exceeded with url: /v1/projects/cloud-dev-112233?alt=json (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x102f98090>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known'))
2023-07-03 13:25:54,570 DEBUG    root            Retrying request to url https://cloudresourcemanager.googleapis.com/v1/projects/cloud-dev-112233?alt=json after exception HTTPSConnectionPool(host='cloudresourcemanager.googleapis.com', port=443): Max retries exceeded with url: /v1/projects/cloud-dev-112233?alt=json (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x102f98090>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known'))
2023-07-03 13:26:07,202 DEBUG    urllib3.connectionpool Starting new HTTPS connection (1): cloudresourcemanager.googleapis.com:443
2023-07-03 13:27:05,590 DEBUG    urllib3.connectionpool https://cloudresourcemanager.googleapis.com:443 "GET /v1/projects/cloud-dev-112233?alt=json HTTP/1.1" 200 None
2023-07-03 13:27:05,611 DEBUG    root            Chosen display Format:default value(name)
2023-07-03 13:27:05,614 INFO     root            Display format: "default value(name)"
2023-07-03 13:27:05,615 INFO     ___FILE_ONLY___ cloud-dev

2023-07-03 13:27:05,631 DEBUG    root            Metrics reporting process started...
